apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/node.yaml
  - k8s/control.yaml

secretGenerator:
  - name: id-rsa
    files:
      - secret/id_rsa
      - secret/id_rsa.pub
      - secret/authorized_keys
