apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node # has to match .spec.template.metadata.labels
  serviceName: "node"
  replicas: 5
#  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: node # has to match .spec.selector.matchLabels
    spec:
#      terminationGracePeriodSeconds: 10
      containers:
        - name: node
          image: jepsen-node
          # Not sure why this is needed, but the compose file adds it.
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - mountPath: /run
              name: run
#            - mountPath: /run/lock
#              name: run-lock
#            - name: ssh-secrets
            - name: ssh-secrets
              mountPath: /root/.ssh/authorized_keys
              subPath: authorized_keys
              readOnly: true
      volumes:
        - name: run
          emptyDir:
            sizeLimit: 100M
#        - name: run-lock
#          emptyDir:
#            sizeLimit: 100M
        - name: ssh-secrets
          secret:
            # Because OpenSSL strictly requires locked down permissions on its .ssh directory,
            # we must ensure that these secrets get mounted with the appropriate permissions.
            defaultMode: 0600
            secretName: id-rsa

---

apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  ports:
    - port: 22
      name: ssh
  clusterIP: None
  selector:
    app: node